const bleachData = [
  // Bleach images
  { id: 1, src: require('./assets/Bleach/bleach1.jpg') },
  { id: 2, src: require('./assets/Bleach/bleach2.jpg') },
  { id: 3, src: require('./assets/Bleach/bleach3.jpg') },
  { id: 4, src: require('./assets/Bleach/bleach4.jpg') },
  { id: 5, src: require('./assets/Bleach/bleach5.jpg') },
  { id: 6, src: require('./assets/Bleach/bleach6.jpg') },
  { id: 7, src: require('./assets/Bleach/bleach7.jpg') },
  { id: 8, src: require('./assets/Bleach/bleach8.jpg') },
  { id: 9, src: require('./assets/Bleach/bleach9.jpg') },
  { id: 10, src: require('./assets/Bleach/bleach10.jpg') },
  { id: 11, src: require('./assets/Bleach/bleach11.jpg') },
  { id: 12, src: require('./assets/Bleach/bleach12.jpg') },
  { id: 13, src: require('./assets/Bleach/bleach13.jpg') },
  { id: 14, src: require('./assets/Bleach/bleach14.jpg') },
  { id: 15, src: require('./assets/Bleach/bleach15.jpg') },
  { id: 16, src: require('./assets/Bleach/bleach16.jpg') },
  { id: 17, src: require('./assets/Bleach/bleach17.jpg') },
  { id: 18, src: require('./assets/Bleach/bleach18.jpg') },
  { id: 19, src: require('./assets/Bleach/bleach19.jpg') },
  { id: 20, src: require('./assets/Bleach/bleach20.jpg') },
  { id: 21, src: require('./assets/Bleach/bleach21.jpg') },
  { id: 22, src: require('./assets/Bleach/bleach22.jpg') },
  { id: 23, src: require('./assets/Bleach/bleach23.jpg') },
  { id: 24, src: require('./assets/Bleach/bleach24.jpg') },
  { id: 25, src: require('./assets/Bleach/bleach25.jpg') },
  { id: 26, src: require('./assets/Bleach/bleach26.jpg') },

  // Mha images
  { id: 27, src: require('./assets/Mha/mha1.jpg') },
  { id: 28, src: require('./assets/Mha/mha2.jpg') },
  { id: 29, src: require('./assets/Mha/mha3.jpg') },
  { id: 30, src: require('./assets/Mha/mha4.jpg') },
  { id: 31, src: require('./assets/Mha/mha5.jpg') },
  { id: 32, src: require('./assets/Mha/mha6.jpg') },
  { id: 33, src: require('./assets/Mha/mha7.jpg') },
  { id: 34, src: require('./assets/Mha/mha8.jpg') },
  { id: 35, src: require('./assets/Mha/mha9.jpg') },
  { id: 36, src: require('./assets/Mha/mha10.jpg') },
  { id: 37, src: require('./assets/Mha/mha11.jpg') },
  { id: 38, src: require('./assets/Mha/mha12.jpg') },
  { id: 39, src: require('./assets/Mha/mha13.jpg') },
  { id: 40, src: require('./assets/Mha/mha14.jpg') },
  { id: 41, src: require('./assets/Mha/mha15.jpg') },
  { id: 42, src: require('./assets/Mha/mha16.jpg') },
  { id: 43, src: require('./assets/Mha/mha17.jpg') },
  { id: 44, src: require('./assets/Mha/mha18.jpg') },
  { id: 45, src: require('./assets/Mha/mha19.jpg') },
  { id: 46, src: require('./assets/Mha/mha20.jpg') },
  { id: 47, src: require('./assets/Mha/mha21.jpg') },
  { id: 48, src: require('./assets/Mha/mha22.jpg') },
  { id: 49, src: require('./assets/Mha/mha23.jpg') },
  { id: 50, src: require('./assets/Mha/mha24.jpg') },
  { id: 51, src: require('./assets/Mha/mha25.jpg') },

  // OnePiece images
  { id: 52, src: require('./assets/OnePiece/onepiece1.jpg') },
  { id: 53, src: require('./assets/OnePiece/onepiece2.jpg') },
  { id: 54, src: require('./assets/OnePiece/onepiece3.jpg') },
  { id: 55, src: require('./assets/OnePiece/onepiece4.jpg') },
  { id: 56, src: require('./assets/OnePiece/onepiece5.jpg') },
  { id: 57, src: require('./assets/OnePiece/onepiece6.jpg') },
  { id: 58, src: require('./assets/OnePiece/onepiece7.jpg') },
  { id: 59, src: require('./assets/OnePiece/onepiece8.jpg') },
  { id: 60, src: require('./assets/OnePiece/onepiece9.jpg') },
  { id: 61, src: require('./assets/OnePiece/onepiece10.jpg') },
  { id: 62, src: require('./assets/OnePiece/onepiece11.jpg') },
  { id: 63, src: require('./assets/OnePiece/onepiece12.jpg') },
  { id: 64, src: require('./assets/OnePiece/onepiece13.jpg') },
  { id: 65, src: require('./assets/OnePiece/onepiece14.jpg') },
  { id: 66, src: require('./assets/OnePiece/onepiece15.jpg') },
  { id: 67, src: require('./assets/OnePiece/onepiece16.jpg') },
  { id: 68, src: require('./assets/OnePiece/onepiece17.jpg') },
  { id: 69, src: require('./assets/OnePiece/onepiece18.jpg') },
  { id: 70, src: require('./assets/OnePiece/onepiece19.jpg') },
  { id: 71, src: require('./assets/OnePiece/onepiece20.jpg') },
  { id: 72, src: require('./assets/OnePiece/onepiece21.jpg') },
  { id: 73, src: require('./assets/OnePiece/onepiece22.jpg') },
  { id: 74, src: require('./assets/OnePiece/onepiece23.jpg') },
  { id: 75, src: require('./assets/OnePiece/onepiece24.jpg') },
];

export default bleachData;

// No unused imports or redundant code found in ImageData1.jsx, preserved all comments
